name: Build RPI

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: pguyot/arm-runner-action@v2.3.1 
      id: build_image
      with:
        base_image: raspios_lite:latest
        image_additional_mb: 4000
        bind_mount_repository: true
        import_github_env: true
        commands: |
            ls -a
            mkdir build 
            cd build
            apt install cmake
            cmake -DDISABLE_CRYPTO=1 ..
            mkdir UVGRTP-package
            sudo make DESTDIR=UVGRTP-package -j4 install
            fpm -a armhf -s dir -t deb -n UVGRTP -v 0.1 -C UVGRTP-package -p UVGRTP_VERSION_ARCH.deb


    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "UVGRTP"
        path: |
          build/*.deb
          *.log


    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-2-evo"
        distro: "raspbian"
        release: "bullseye"
        republish: "true" # needed ONLY if version is not changing
        file: "build/*.deb"


      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
